### ISSUE TITLE
Conflict filenames between analysis and disciplinary

### ISSUE THREAD

**Issue by sverley** [OneraHub/WhatsOpt#57]
When you creates an analysis with a disciplinary with the same name, the generated code doesn't provide the disciplinary file since it should have the same name than the analysis.

I suggest to export filenames with suffix for one of analysis or disciplinary files.

**Comment by sverley** [comment]
Of course, an easy and direct workaround is to have different names for analysis and disciplinary. Be aware that if you already has `wop pull` the analysis, you will have to remove the conflicted file before you `wop update`

**Comment by relf** [comment]
Thanks for reporting. So far I've made little effort to avoid such conflict names as you suggest the workaround is pretty easy 

I could add `_mda` to the analysis name to get something like `<analysis>_mda.py`. But one could argue it could be defeated by a discipline named `<Analysis>Mda`, maybe a conflict less frequent than the previous one though. We can imagine more complex management but it would be more... complex and this does not appear to be a strong problem at the moment.

**Comment by relf** [comment]
I close this one. Even `_mda` addition does not seem to be worth taking the risk of a breaking change for existing code.
