### ISSUE TITLE
GUI: variable table: Need for keeping column names visible with large number of variables

### ISSUE THREAD

**Issue by christophe-david** [OneraHub/WhatsOpt#62]
Having a use case with lots of variables, I would appreciate to have the title row always visible, especially in edit mode, to be sure to know what fields I am modifying.

**Comment by relf** [comment]
Ok I made some tests on this one. The widget I use to display the table allow several solutions to tackle this issue.

The first, coming from your statement is to virtualize rows to keep table headers fixed and add a scroll to the table. My first try at this is not very good. It requires using `<div>` elements for the table implying a rework of the styling which is currently beyond my knowledge.

So I think to address this issue by adding pagination. You would be able to select a number of row to be displayed and got to the relevant page.

Another option (which I think I may end up to implement anyway) would be to add filtering: you enter a variable name or more conveniently a substring matching variable names and the rows are filtered accordingly.

**Comment by christophe-david** [comment]
Thanks for the feedback.
I would definitely be happy with a substring-based filtering!
