### ISSUE TITLE
GUI: variable table: could column widths be controlled ?

### ISSUE THREAD

**Issue by christophe-david** [OneraHub/WhatsOpt#63]
Having a use case with (very) long variable names, I would appreciate to be able to modify the width of some columns in the variable table.

**Comment by relf** [comment]
Reference #74, follow-up of #72

**Comment by relf** [comment]
Column name has been widen and together with filtering and pagination, it seems to be sufficient to make the GUI acceptable. Allowing columns resizing would required a complete rework of the table styling which is too much regarding the benefits at the moment.
