### ISSUE TITLE
Generated code: specification of units

### ISSUE THREAD

**Issue by christophe-david** [OneraHub/WhatsOpt#82]
Hello, 
in generated code for OpenMDAO, I would greatly appreciate if units could be specified in following methods:
- `set_input_defaults()`
- `add_design_var()`
- `add_objective()`
- `add_constraint()`

**Comment by relf** [comment]
You did not mention `add_input` and `add_output` at component level, though WhatsOpt could enforce it here too. Whats is the rationale? Does it let the component implementation use compatible units?

**Comment by christophe-david** [comment]
Actually, I don't need any change in these methods in my use case, as I use my own implementation of disciplines. But for sake of consistency, I guess you may declare units in these methods as well.

**Comment by relf** [comment]
`add_input` and `add_output` are in the setup in the base files. Do you override those methods when use your implementations? How does it work when you use compatible but different units than the ones specified by WhatsOpt?

**Comment by christophe-david** [comment]
> `add_input` and `add_output` are in the `setup` in the base files. Do you override this method when you use your implementations? 

I override the `create_*()` methods to use my own implementations of the disciplines, that do not inherit from the base classes. Therefore, the generated base classes for these disciplines are not used. Of course, I know that in such case, I am responsible for keeping my inputs and outputs consistent.

> If not how does it work if you use compatible but different units than the ones specified by WhatsOpt in the setup?

Currently, it does not work, that's the point 😁. But once the inputs will have been declared with proper units, OpenMDAO will gracefully do the conversion, and then, it will be great!

**Comment by relf** [comment]
Ok, I will also add units at component level (it was my concern in the first place it gets in the way if I do). And you can test right now as the feature is deployed.

**Comment by christophe-david** [comment]
Many thanks. I will test that very soon!
